on: 
  issue_comment:
    types: [created]
name: Claim Issue
jobs:
  assign:
    name: Update labels and Assign
    if: github.event.issue.pull_request == '' 
      && contains(github.event.comment.body, '/claim') 
      && contains(toJson(github.event.issue.labels), 'Available')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        env:
          username: ${{ github.actor }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Status: Claimed']
              })
            await github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Status: Available'
              })
            await github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [process.env.username]
              })
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you @'+process.env.username+' for claiming this issue! ðŸŽ‰ \n\nPlease reference this issue when you submit your Pull Request.'
            })
